###############################################
# Note this file is a template and should be  #
# updated with the actual content             #
###############################################

# Filename: competency-queries.sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://example.org/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

###############################################
# Note this file is a template and should be  #
# updated with the actual version information #
###############################################

# Write your validation (competency) queries below.
SELECT ?s ?p
WHERE {
  ?s rdf:type ex:Class .
  ?p rdfs:domain ?s .
  MINUS { ?s ?p ?o }
}
